export const PRODUCTS_FETCH_INITIATED = "PRODUCTS_FETCH_INITIATED";
export const PRODUCTS_FETCH_SUCCEEDED = "PRODUCTS_FETCH_SUCCEEDED";
export const PRODUCTS_FETCH_FAILED = "PRODUCTS_FETCH_FAILED";

export const PRODUCT_DELETE_INITIATED = "PRODUCT_DELETE_INITIATED";
export const PRODUCT_DELETE_SUCCEEDED = "PRODUCT_DELETE_SUCCEEDED";
export const PRODUCT_DELETE_FAILED = "PRODUCT_DELETE_FAILED";

export const PRODUCT_FETCH_INITIATED = "PRODUCT_FETCH_INITIATED";
export const PRODUCT_FETCH_SUCCEEDED = "PRODUCT_FETCH_SUCCEEDED";
export const PRODUCT_FETCH_FAILED = "PRODUCT_FETCH_FAILED";